app/modules/users/engineer/routes.py
from flask import Blueprint, request, render_template, redirect, url_for, flash, session, send_file
import pymongo
import os
import pandas as pd
from io import BytesIO

engineer_bp = Blueprint('engineer', __name__)

db_username = os.environ.get('DB_USERNAME', None)
db_password = os.environ.get('DB_PASSWORD', None)
client = pymongo.MongoClient(f"mongodb+srv://{db_username}:{db_password}@team2interactivetables.g85jafu.mongodb.net/?retryWrites=true&w=majority&appName=Team2InteractiveTables")
db_Cover = client.get_database("Cover")
residents_db = db_Cover['Residents']

db_Sensor = client.get_database("Data")
sensors_collection = db_Sensor['Sensor_Data']

@engineer_bp.route('/ResidentsInfo')
def ResidentsInfo():
    if 'username' not in session:
        flash('You need to log in first', 'danger')
        return redirect(url_for('users.login'))

    residents = list(residents_db.find())

    building_counts = residents_db.aggregate([
        {"$group": {"_id": "$Building", "count": {"$sum": 1}}}
    ])
    building_counts_dict = {doc['_id']: doc['count'] for doc in building_counts if doc['_id']}  # Skip empty building names

    return render_template('ResidentsInfo.html', username=session['username'], residents=residents, building_counts=building_counts_dict)

@engineer_bp.route('/export_residents')
def export_residents():
    if 'username' not in session:
        flash('You need to log in first', 'danger')
        return redirect(url_for('users.login'))

    residents = list(residents_db.find({}, {'_id': 0, 'Name': 1, 'Surname': 1, 'Phone': 1, 'Building': 1, 'Email': 1}))
    df = pd.DataFrame(residents)

    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
        df.to_excel(writer, index=False, sheet_name='Residents')

    buffer.seek(0)
    return send_file(buffer, as_attachment=True, download_name='residents.xlsx', mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

@engineer_bp.route('/preview_export', methods=['GET'])
def preview_export():
    if session.get('username') != 'engineer':
        return redirect(url_for('users.dashboard'))

    sensor_data = list(sensors_collection.find({}))
    df = pd.DataFrame(sensor_data)

    return render_template('preview_export.html', tables=df.to_html(classes='table table-striped', index=False))

@engineer_bp.route('/export')
def export():
    if session.get('username') != 'engineer':
        return redirect(url_for('users.dashboard'))

    sensor_data = list(sensors_collection.find({}))
    df = pd.DataFrame(sensor_data)

    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
        df.to_excel(writer, index=False, sheet_name='Sensor Data')

        workbook = writer.book
        worksheet = writer.sheets['Sensor Data']

        worksheet.write('K1', 'Summary')
        worksheet.write('K2', 'Average Temperature')
        worksheet.write('L2', df['Temperature'].mean())
        worksheet.write('K3', 'Average Vibration')
        worksheet.write('L3', df['Vibration SD'].mean())

    buffer.seek(0)
    return send_file(buffer, as_attachment=True, download_name='sensor_data.xlsx', mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')


@engineer_bp.route('/abnormal_data', methods=['GET'])
def abnormal_data():
    # if session.get('username') != 'engineer]:
    #     return redirect(url_for('users.dashboard'))


    # Get the filter values from the query parameters
    temperature_threshold = request.args.get('temperature', type=float, default=28.5)
    vibration_threshold = request.args.get('vibration', type=float, default=0.001)
    tilt_threshold = request.args.get('tilt', type=float, default=2.0) 

    sensor_data = list(sensors_collection.find({}))
    df = pd.DataFrame(sensor_data)

    df['Temperature'] = pd.to_numeric(df['Temperature'], errors='coerce')
    df['Vibration SD'] = pd.to_numeric(df['Vibration SD'], errors='coerce')
    df['Tilt'] = pd.to_numeric(df['Tilt'], errors='coerce')  # Assuming 'Tilt' is a column in your DataFrame


     # Apply user-defined filtering
    filtered_df = df[(df['Temperature'] > temperature_threshold) | (df['Vibration SD'] > vibration_threshold) |
    (df['Tilt'] > tilt_threshold)]

    print("DataFrame Head:\n", filtered_df.head())
    return render_template('abnormal_data.html', tables=filtered_df.to_html(classes='table table-striped', index=False))

@engineer_bp.route('/export_abnormal_data')
def export_abnormal_data():
    if 'username' not in session:
        flash('You need to log in first', 'danger')
        return redirect(url_for('users.login'))

    sensor_data = list(sensors_collection.find({}))
    df = pd.DataFrame(sensor_data)

    df['Temperature'] = pd.to_numeric(df['Temperature'], errors='coerce')
    df['Vibration SD'] = pd.to_numeric(df['Vibration SD'], errors='coerce')
    df['Tilt'] = pd.to_numeric(df['Tilt'], errors='coerce')  # Assuming 'Tilt' is a column in your DataFrame


    filtered_df = df[(df['Temperature'] > 28.5) | (df['Vibration SD'] > 0.001) | (df['Tilt'] > 1.0)]

    buffer = BytesIO()
    with pd.ExcelWriter(buffer, engine='xlsxwriter') as writer:
        filtered_df.to_excel(writer, index=False, sheet_name='Abnormal Data')

    buffer.seek(0)
    return send_file(buffer, as_attachment=True, download_name='abnormal_data.xlsx', mimetype='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')

app/modules/users/routes.py
from datetime import datetime, timedelta
import json
from flask import Blueprint, jsonify, request, render_template, redirect, url_for, flash, session,make_response
import pymongo
from ..api.auth import get_access_token
from ..api.client import get_sensor_readings, insert_data_to_mongodb, is_token_valid, load_data_from_file, retrieve_token_from_db, save_to_file, save_to_mongodb, save_token_to_db, insert_data_from_jason
from .models import User
import os

users_bp = Blueprint('users', __name__)

db_username = os.environ.get('DB_USERNAME', None)
db_password = os.environ.get('DB_PASSWORD', None)
client = pymongo.MongoClient(f"mongodb+srv://{db_username}:{db_password}@team2interactivetables.g85jafu.mongodb.net/?retryWrites=true&w=majority&appName=Team2InteractiveTables")
db = client.get_database("Cover")

user_model = User(db)

@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = user_model.find_user(username, password)
        if user:
            session['username'] = username
            session['name'] = user['Name']  # Store user's name in session
            if username == 'engineer':
                session['user_role'] = 'engineer'
            elif username == 'kabat':
                session['user_role'] = 'securityMan'
            else:
                session['user_role'] = 'resident'
            flash('Login successful!', 'success')
            return redirect(url_for('users.dashboard'))
        else:
            flash('Invalid username or password', 'danger')
            return render_template('login.html', error="Invalid username or password")
    return render_template('login.html')

@users_bp.route('/change_password', methods=['GET', 'POST'])
def change_password():
    if request.method == 'POST':
        email = request.form['email']
        username = request.form['username']
        old_password = request.form['old_password']
        new_password = request.form['new_password']
        
        user = user_model.find_user(username, old_password)
        
        if user and user['email'] == email:
            user_model.update_password(username, new_password)
            flash('Password successfully changed!', 'success')
            return redirect(url_for('users.dashboard'))
        else:
            flash('Invalid credentials. Please try again.', 'danger')
    
    return render_template('change_password.html')

@users_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        if user_model.find_user_by_username(username):
            flash('Username already exists', 'danger')
            return redirect(url_for('users.register'))
        else:
            user_model.insert_user(username, password)
            flash('Registration successful! Please log in.', 'success')
            return redirect(url_for('users.login'))
    return render_template('register.html')

@users_bp.route('/dashboard')
def dashboard():
    if 'username' in session:
        return render_template('index.html', username=session['username']) 
    else:
        flash('You need to log in first', 'danger')
        return redirect(url_for('users.login'))

@users_bp.route('/logout')
def logout():
    session.pop('username', None)
    flash('You have been logged out', 'success')
    return redirect(url_for('users.login'))

@users_bp.route('/forgot_password')
def forgot_password():
    return "Forgot Password page (to be implemented)"

@users_bp.route('/refresh_API_data', methods=['POST'])
def refresh_API_data():
    email = "sce@atomation.net"
    password = "123456"
    mac_addresses = ["C8:FD:9D:A5:27:FB"]
    start_date = "2024-08-16T00:00:00.000Z"
    end_date = "2024-08-18T09:50:50.000Z"

    try:
        # token = retrieve_token_from_db(client)
        # if not token or not is_token_valid(token):
        #     token = get_access_token(email, password)
        #     print(token)
        #     save_token_to_db(token, client)
        # sensor_readings = get_sensor_readings(token, mac_addresses, start_date, end_date)
        # if 'data' in sensor_readings and 'readings_data' in sensor_readings['data']:
        #     sensor_readings = sensor_readings['data']['readings_data']
        #     print(sensor_readings)
        #     save_to_file(sensor_readings, "sensor_readings_aug.json")
        # insert_data_to_mongodb(client, sensor_readings)
        with open('sensor_readings_aug.json', 'r') as file:
            print("im in open the file")
            json_data = json.load(file)
            #readings = json_data['data']['readings_data']  # Access the list of readings
            for reading in json_data:
                print(reading)
        # Insert each reading into MongoDB
        for reading in json_data:
            insert_data_from_jason(client,reading)

        return "Data refresh successful"
    except Exception as e:
        print(e)
        return "Something went wrong"

@users_bp.route('/')
def index():
    return render_template('index.html')

@users_bp.route('/data')
def get_data():
    month = request.args.get('month')
    date = request.args.get('date')
    db = client.get_database("Data")
    collection = db['Sensor_Data']
    
    if date:
        # Handle date filtering
        start_date = f"{date}T00:00:00.000Z"
        end_date = f"{date}T23:59:59.999Z"
        data = list(collection.find(
            {"sample_time_utc": {"$gte": start_date, "$lt": end_date}},
            {'_id': 0, 'Temperature': 1, 'Vibration SD': 1, 'Tilt': 1, 'sample_time_utc': 1}
        ))
        print(f"Retrieved {len(data)} records for date: {date}")
    elif month:
        # Handle month filtering
        year, month = map(int, month.split('-'))
        start_date = f"{year:04d}-{month:02d}-01T00:00:00.000Z"
        if month == 12:
            end_date = f"{year + 1:04d}-01-01T00:00:00.000Z"
        else:
            end_date = f"{year:04d}-{month + 1:02d}-01T00:00:00.000Z"
        
        data = list(collection.find(
            {"sample_time_utc": {"$gte": start_date, "$lt": end_date}},
            {'_id': 0, 'Temperature': 1, 'Vibration SD': 1, 'Tilt': 1, 'sample_time_utc': 1}
        ))
        print(f"Retrieved {len(data)} records for month: {month}")
    else:
        data = list(collection.find({}, {'_id': 0, 'Temperature': 1, 'Vibration SD': 1, 'Tilt': 1, 'sample_time_utc': 1}))

    return jsonify(data)



@users_bp.route('/logout', methods=['GET'], endpoint='logout_user')
def logout():
    session.clear()
    flash('You have been logged out', 'success')
    response = make_response(redirect(url_for('users.login')))
    response.headers['Cache-Control'] = 'no-store, no-cache, must-revalidate, max-age=0'
    response.headers['Pragma'] = 'no-cache'
    response.headers['Expires'] = '0'
    return response

app/templates/partials/sidebar.html
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{{ url_for('users.index') }}">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-tachometer-alt"></i>
        </div>
        <div class="sidebar-brand-text mx-3">Cover <sup></sup></div>
    </a>


    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{{ url_for('users.index') }}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Home</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">



    <!-- Nav Item - Pages Collapse Menu -->
     <!----
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
        
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fas fa-fw fa-envelope"></i>
            <span><a href="mailto:omeraluf@gmail.com" target="_blank">Contact Us</a></span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Custom Components:</h6>
                <a class="collapse-item" href="buttons.html">Buttons</a>
                <a class="collapse-item" href="cards.html">Cards</a>
            </div>
        </div>
    </li>
>
    <!-- Nav Item - Utilities Collapse Menu -->
    {% if session['user_role'] == 'resident' %}
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('resident.contactUs') }}">
            <i class="fas fa-fw fa-envelope"></i>
            <span>Contact us</span></a>
    </li>
    {% endif %} 

 
    {% if session['user_role'] == 'engineer' or session['user_role'] == 'securityMan' %}
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('engineer.abnormal_data') }}">
            <i class="fas fa-fw fa-calendar-alt"></i>
            <span>Abnormal data</span></a>
    </li>
    {% endif %} 
    <!-- New Nav Item - Monthly Snapshot -->
    {% if session['user_role'] == 'resident' %}
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('resident.monthly_snapshot') }}">
            <i class="fas fa-fw fa-calendar-alt"></i>
            <span>Monthly Snapshot</span></a>
    </li>
    {% endif %} 

    {% if session['user_role']  == 'engineer' %}
    <li class="nav-item">
        <a class="nav-link" href="{{ url_for('engineer.preview_export') }}">
            <i class="fas fa-fw fa-download"></i>
            <span>Export Sensor Data</span>
        </a>
    </li>
    {% endif %} 

    <!-- New Nav Item - Monthly Snapshot -->
    {% if session['user_role'] == 'engineer' or session['user_role'] == 'securityMan' %}
        <li class="nav-item">
            <a class="nav-link" href="{{ url_for('engineer.ResidentsInfo') }}">
                <i class="fas fa-fw fa-calendar-alt"></i>
                <span>Residents Information</span>
            </a>
        </li>
    {% endif %}

    {% if session['user_role'] == 'securityMan' %}
    <li class="nav-item">
        <a href="#" class="nav-link" onclick="sendEmail(); return false;">
            <i class="fas fa-fw fa-exclamation-circle"></i>
            <span>Report Broken Sensor</span>
        </a>
    </li>
    {% endif %}

    {% if session['user_role'] == 'securityMan' %}
    <li class="nav-item">
        <a href="#" class="nav-link" id="sendDailyReportButton">
            <i class="fas fa-fw fa-envelope"></i>
            <span>Day Summary</span>
        </a>
    </li>
    {% endif %}

    <script>
    function sendEmail() {
        var email = 'automation@gmail.com';
        var subject = encodeURIComponent('Sensor Alert');
        var body = encodeURIComponent('Sensor number 1 is broken');
        var mailtoLink = 'mailto:' + email + '?subject=' + subject + '&body=' + body;
        window.location.href = mailtoLink;
        alert("An email attempt has been made. Please check your email client to complete the process.");
    }
    </script>

<script>
    document.getElementById('sendDailyReportButton').addEventListener('click', function(event) {
        event.preventDefault();  // Prevent default link behavior
        fetch('/security/send_daily_report', {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                alert('Email sent successfully.');
            } else {
                alert(`Error: ${data.message}`);
            }
        })
        .catch(error => {
            console.error('Error:', error);
            alert('An error occurred while sending the daily report.');
        });
    });
</script>

</ul>
<!-- End of Sidebar -->

app/templates/partials/topbar.html
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <!-- Topbar Navbar -->
    <!-- <ul class="navbar-nav ml-auto"> -->
    <ul class="navbar-nav ml-auto">


        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
         <!------
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>
>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Welcome, {{ session['name'] if 'name' in session else 'Guest' }}</span>
                <i class="fas fa-laugh-wink"></i>
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{{ url_for('users.change_password') }}">
                    <i class="fas fa-key fa-fw"></i>
                    Change Password
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('users.logout')}}">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>


    </ul>

</nav>
<!-- End of Topbar -->